#!/bin/env sh

#sensors | grep "Package id 0:" | tr -d '+' | awk '{print $4}'
#  $(grep 'cpu ' /proc/stat | awk '{cpu_usage=($2+$4)*100/($2+$4+$5)}
#        END {printf "%0.2f%", cpu_usage}')
case "$1" in
    --popup)
        notify-send "CPU time (%)" "$(ps axch -o cmd:10,pcpu k -pcpu | head | awk '$0=$0"%"' )"
        ;;
    *)
        echo "$(sensors | grep "Package id 0:" | tr -d '+' | awk '{print $4}')"
        ;;
esac
